### ISSUE TITLE
Dilger respond to questions

### ISSUE THREAD

**Issue by cbdilger** [seo33/IMLeagues#2]
Dilger    !!!!!!

https://docs.google.com/document/d/143zxP2kiWLuYKN-U7rKvAR87kLxXlGjBkO0YFiOniuM/edit

**Comment by seo33** [comment]
Hey Bradley, we will greatly appreciate it if you could provide us with some feedback before our group meeting on Sunday!

**Comment by cbdilger** [comment]
On it. I'm going to put the answers in the Google Doc.

**Comment by cbdilger** [comment]
@seo33 @coyprice — I think I've responded to all your questions. If so, please close this issue.
